name: Proposer une idée ou participer
description: Une meilleure explication, une source, une nouvelle page ou fonctionnalité, ou l'envie d'y participer.
title: "[Idée] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idee
    attributes:
      label: Ton idée ou ta proposition
    validations:
      required: true
  - type: dropdown
    id: participer
    attributes:
      label: Envie d'y participer ?
      options:
        - Non, juste l'idée
        - Oui, pour les données ou les explications
        - Oui, pour le code
    validations:
      required: false
